version: "3"

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - /var/www/vendor/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8086:80"
    depends_on:
      - app
    container_name: rentaflat_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
      - ./vendor:/var/www/vendor/
      - ./storage:/var/www/storage
    depends_on:
      - db
    container_name: rentaflat_app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: rentaflat_db
      MYSQL_ROOT_PASSWORD: festival567
      MYSQL_USER: rentaflat_user
      MYSQL_PASSWORD: festival567
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: rentaflat_db

  vite_docker:
    image: node:alpine
    container_name: rentaflat_vite
    entrypoint: /bin/sh
    ports:
        - 5173:5173
    working_dir: /var/www/public/
    volumes:
        - type: bind
          source: ./
          target: /var/www/
    tty: true
